//tracks projectile hits ? original name: aa.q
SR_Projectile.prototype.PJsub = function(a) {
    this.PJ_attacker[a] = this.PJ_attacker[this.PJ_index-1];
    this.PJ_position[a].Vset(this.PJ_position[this.PJ_index-1]);
    this.PJ_velocity[a].Vset(this.PJ_velocity[this.PJ_index-1]);
    this.PJ_is_transparent[a] = this.PJ_is_transparent[this.PJ_index-1];
    this.PJ_orient[a] = this.PJ_orient[this.PJ_index-1];
    this.PJ_img[a] = this.PJ_img[this.PJ_index-1];
    this.PJ_color[a] = this.PJ_color[this.PJ_index-1];
    this.PJ_transp[a] = this.PJ_transp[this.PJ_index-1];
    this.PJ_width[a] = this.PJ_width[this.PJ_index-1];
    this.PJ_height[a] = this.PJ_height[this.PJ_index-1];
    this.PJ_box_width[a] = this.PJ_box_width[this.PJ_index-1];
    this.PJ_box_height[a] = this.PJ_box_height[this.PJ_index-1];
    this.PJ_appear_delay[a] = this.PJ_appear_delay[this.PJ_index-1];
    this.PJ_solid_delay[a] = this.PJ_solid_delay[this.PJ_index-1];
    this.PJ_lifespan[a] = this.PJ_lifespan[this.PJ_index-1];
    this.PJ_disp_eff[a] = this.PJ_disp_eff[this.PJ_index-1];
    this.PJ_gravity[a] = this.PJ_gravity[this.PJ_index-1];
    this.PJ_accel[a] = this.PJ_accel[this.PJ_index-1];
    this.PJ_pierce[a] = this.PJ_pierce[this.PJ_index-1];
    this.PJ_bounce[a] = this.PJ_bounce[this.PJ_index-1];
    this.PJ_homing[a] = this.PJ_homing[this.PJ_index-1];
    this.PJ_is_critical[a] = this.PJ_is_critical[this.PJ_index-1];
    this.PJ_knockback[a] = this.PJ_knockback[this.PJ_index-1];
    this.PJ_splash[a] = this.PJ_splash[this.PJ_index-1];
    this.PJ_AT_min[a] = this.PJ_AT_min[this.PJ_index-1];
    this.PJ_AT_max[a] = this.PJ_AT_max[this.PJ_index-1];
    this.PJ_res_type[a] = this.PJ_res_type[this.PJ_index-1];
    this.PJ_res_type_param[a] = this.PJ_res_type_param[this.PJ_index-1];
    this.PJ_res_mode[a] = this.PJ_res_mode[this.PJ_index-1];
    this.PJ_res_orient[a] = this.PJ_res_orient[this.PJ_index-1];
    this.PJ_res_img[a] = this.PJ_res_img[this.PJ_index-1];
    this.PJ_res_color[a] = this.PJ_res_color[this.PJ_index-1];
    this.PJ_res_transp[a] = this.PJ_res_transp[this.PJ_index-1];
    this.PJ_res_width[a] = this.PJ_res_width[this.PJ_index-1];
    this.PJ_res_height[a] = this.PJ_res_height[this.PJ_index-1];
    this.PJ_res_box_width[a] = this.PJ_res_box_width[this.PJ_index-1];
    this.PJ_res_box_height[a] = this.PJ_res_box_height[this.PJ_index-1];
    this.PJ_res_appear_delay[a] = this.PJ_res_appear_delay[this.PJ_index-1];
    this.PJ_res_solid_delay[a] = this.PJ_res_solid_delay[this.PJ_index-1];
    this.PJ_res_lifespan[a] = this.PJ_res_lifespan[this.PJ_index-1];
    this.PJ_res_fade_tick[a] = this.PJ_res_fade_tick[this.PJ_index-1];
    this.PJ_res_grav[a] = this.PJ_res_grav[this.PJ_index-1];
    this.PJ_res_accel[a] = this.PJ_res_accel[this.PJ_index-1];
    this.PJ_res_pierce[a] = this.PJ_res_pierce[this.PJ_index-1];
    this.PJ_res_bounce[a] = this.PJ_res_bounce[this.PJ_index-1];
    this.PJ_res_splash[a] = this.PJ_res_splash[this.PJ_index-1];
    this.PJ_res_AT_min[a] = this.PJ_res_AT_min[this.PJ_index-1];
    this.PJ_res_AT_max[a] = this.PJ_res_AT_max[this.PJ_index-1];
    this.PJ_res_bullet[a] = this.PJ_res_bullet[this.PJ_index-1];
    this.PJ_res_base_type[a] = this.PJ_res_base_type[this.PJ_index-1];
    this.PJ_res_base_type_param[a] = this.PJ_res_base_type_param[this.PJ_index-1];
    this.PJ_index--;
};
