var Projectiles = new SR_Projectile;
function SR_Projectile(){ // original name: ih()
    this.PJ_index = 0;                                        // original name: .index
    this.PJ_attacker = new Int32Array(Proj_Limit);            // original name: .F
    this.PJ_position = Array(Proj_Limit);                     // original name: .a
    this.PJ_velocity = Array(Proj_Limit);                     // original name: .k
    this.PJ_is_transparent = new Int32Array(Proj_Limit);      // original name: .d
    this.PJ_orient = new Int32Array(Proj_Limit);              // original name: .Ya
    this.PJ_img = new Int32Array(Proj_Limit);                 // original name: .N
    this.PJ_color = new Int32Array(Proj_Limit);               // original name: .G
    this.PJ_transp = new Int32Array(Proj_Limit);              // original name: .Wa
    this.PJ_width = new Int32Array(Proj_Limit);               // original name: .Ua
    this.PJ_height = new Int32Array(Proj_Limit);              // original name: .Va
    this.PJ_box_width = new Int32Array(Proj_Limit);           // original name: .ja
    this.PJ_box_height = new Int32Array(Proj_Limit);          // original name: .ka
    this.PJ_appear_delay = new Int32Array(Proj_Limit);        // original name: .ha
    this.PJ_solid_delay = new Int32Array(Proj_Limit);         // original name: .oa
    this.PJ_lifespan = new Int32Array(Proj_Limit);            // original name: .count
    this.PJ_disp_eff = new Int32Array(Proj_Limit);            // original name: .ia
    this.PJ_gravity = new Int32Array(Proj_Limit);             // original name: .e
    this.PJ_accel = new Int32Array(Proj_Limit);               // original name: .i
    this.PJ_pierce = new Int32Array(Proj_Limit);              // original name: .ya
    this.PJ_bounce = new Int32Array(Proj_Limit);              // original name: .Y
    this.PJ_homing = new Int32Array(Proj_Limit);              // original name: .ra
    this.PJ_is_critical = new Int32Array(Proj_Limit);         //  (new variable)
    this.PJ_knockback = new Int32Array(Proj_Limit);           // original name: .la
    this.PJ_splash = new Int32Array(Proj_Limit);              // original name: .ga
    this.PJ_AT_min = new Int32Array(Proj_Limit);              // original name: .ea
    this.PJ_AT_max = new Int32Array(Proj_Limit);              // original name: .fa
    this.PJ_res_type = new Int32Array(Proj_Limit);            // original name: .U
    this.PJ_res_type_param = new Int32Array(Proj_Limit);      // original name: .V
    this.PJ_res_mode = new Int32Array(Proj_Limit);            // original name: .sub
    this.PJ_res_orient = new Int32Array(Proj_Limit);          // original name: .Ha
    this.PJ_res_img = new Int32Array(Proj_Limit);             // original name: .Sa
    this.PJ_res_color = new Int32Array(Proj_Limit);           // original name: .Ea
    this.PJ_res_transp = new Int32Array(Proj_Limit);          // original name: .za
    this.PJ_res_width = new Int32Array(Proj_Limit);           // original name: .Pa
    this.PJ_res_height = new Int32Array(Proj_Limit);          // original name: .Qa
    this.PJ_res_box_width = new Int32Array(Proj_Limit);       // original name: .La
    this.PJ_res_box_height = new Int32Array(Proj_Limit);      // original name: .Ma
    this.PJ_res_appear_delay = new Int32Array(Proj_Limit);    // original name: .Ga
    this.PJ_res_solid_delay = new Int32Array(Proj_Limit);     // original name: .Na
    this.PJ_res_lifespan = new Int32Array(Proj_Limit);        // original name: .Fa
    this.PJ_res_fade_tick = new Int32Array(Proj_Limit);       // original name: .Ia
    this.PJ_res_grav = new Int32Array(Proj_Limit);            // original name: .Ja
    this.PJ_res_accel = new Int32Array(Proj_Limit);           // original name: .Ta
    this.PJ_res_pierce = new Int32Array(Proj_Limit);          // original name: .Oa
    this.PJ_res_bounce = new Int32Array(Proj_Limit);          // original name: .Ka
    this.PJ_res_splash = new Int32Array(Proj_Limit);          // original name: .Ra
    this.PJ_res_AT_min = new Int32Array(Proj_Limit);          // original name: .Aa
    this.PJ_res_AT_max = new Int32Array(Proj_Limit);          // original name: .Ba
    this.PJ_res_bullet = new Int32Array(Proj_Limit);          // original name: .A
    this.PJ_res_base_type = new Int32Array(Proj_Limit);       // original name: .Ca
    this.PJ_res_base_type_param = new Int32Array(Proj_Limit); // original name: .Da
    for (var i=0; i<Proj_Limit; i++){
        this.PJ_velocity[i] = new Vector2D;
        this.PJ_position[i] = new Vector2D;
    }
}
